---
title: "index.Rmd"
output: html_document
date: "2023-10-04"
---

```{r setup, include=FALSE}
library(haven)
library(ggplot2)
library(tidyverse)
library(ggrepel)
library(dplyr)
```

[Data Sources] (https://microdata.worldbank.org/index.php/catalog/3769/get-microdata)

## (ADD TITLE HERE! Take out parantheses)

``` {r}

data <- read_dta('data/learning_loss_covid_database.dta')

# Scatter Plot + Line 
ggplot(data, aes(x = weeks, y = loss)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE, color = "red", linetype = "dashed") +
  theme_minimal(base_family = "Times New Roman") +
  xlab("Average number of weeks of school closure in 2021") + 
  ylab("Decline in test scores") +
  ggtitle("Decline in test scores due to the duration of school closure") +
 theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        plot.background = element_rect(fill = "grey"),  
        panel.background = element_rect(fill = "white")) 

```

```{r}
# Another Version 
  ggplot() +
    geom_point(data, mapping = aes(x = weeks, y = loss)) +
    geom_smooth(data, mapping = aes(x = weeks, y = loss))
```


## Decline in Test Scores By Region During 2021 - Measured in Standard Deviation

```{r, echo=FALSE}

suppressWarnings({ 




custom_colors <- c("olivedrab3", "orange", "steelblue", "pink", "coral", "violet")

data %>%
  ggplot() +
  geom_col(mapping = aes(x = region_code, y = loss, fill = region_code)) +
  scale_fill_manual(values = custom_colors) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title = "Decline in Test Scores By Region 2021",
    subtitle = "Due to COVID school closures",
    x = "Region",
    y = "Decline in Test Scores"
  ) + 
  guides(fill = FALSE)

}) 
```


## Death Versus Vaccination Rates By Region in 2021

```{r second, echo=FALSE}

countries_to_label <- data %>%
  filter(country %in% c("Nepal", "Hungary", "Argentina", "India", "Korea", "United States", "Kenya", "China", "Germany"))

data %>%
  ggplot() +
  geom_point(mapping = aes(x = deaths, y = vac, color = region_code)) +
  geom_text(data = countries_to_label, mapping = aes(x = deaths, y = vac, label = country)) + 
  labs(
    title = "Death Rate Average Compared to Vaccination Rate in 2021",
    subtitle = "Data: https://ourworldindata.org/grapher/covid-vaccination-doses-per-capita",
    x = "Deaths Rate Average",
    y = "Vaccination Rate - Doses per Capita"
  ) 
  
```



```{r}
data %>%
  ggplot(mapping = aes(x = "", y = internet, fill = region_code)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  theme_void(base_family = "Times New Roman") +
  ggtitle("Internet penetration by region") +
 theme(plot.title = element_text(hjust = 0.5),
        legend.position = "right",
        legend.title = element_blank(),
        plot.background = element_rect(fill = "grey"),  
        panel.background = element_rect(fill = "white")) 
#trying to add % share on the pie chart 
```

